package game;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

import javax.swing.JFrame;
import javax.swing.JPanel;

import view.GameboardView;
import view.PlayerView;
import view.PropertyView;

public class GUI extends JFrame{
	/**
	 * autogenerated serial id. idk why
	 */
	private static final long serialVersionUID = 1L;
	PlayerView playerView;
	PropertyView propView;
	GameboardView gameboardView;
	 JPanel gameBoard;
     JPanel centerPanel ;
	
	
	public GUI(	PlayerView playerView,PropertyView propView,GameboardView gameboardView){
		super("Brandon's Slumlord Adventure");
		
		this.playerView =  playerView;
		this.propView = propView;
		this.gameboardView = gameboardView;
		
		 setLayout(new GridBagLayout());
		 generateBoard();
		
	}
	private void generateBoard(){
		
	  
	    GridBagConstraints c = new GridBagConstraints();
	  
	 
	    gameBoard = new JPanel();
	    gameBoard.setOpaque(true);
	    gameBoard.setBackground(Color.cyan);
	    gameBoard.add(gameboardView.getTopPanel());
	  
	   
	   c.fill = GridBagConstraints.BOTH;
	  
	   c.gridwidth = 6;
	   // c.gridheight =  1;
	   c.gridx = 0;
	    c.gridy = 0;
	    c.weightx = 1;
	  c.weighty = 1;
	   
	    add(gameBoard,c);
	    
	    gameBoard = new JPanel();
	    gameBoard.setOpaque(true);
	    gameBoard.setBackground(Color.cyan);
	    gameBoard.add(gameboardView.getBottomPanel());
	  
	   c.fill = GridBagConstraints.BOTH;

	    c.gridx = 0;
	    c.gridy = 4;
	    c.gridwidth = 6; 
	    c.weightx = 1;
	  c.weighty = 1;
	   
	    add(gameBoard,c);
	    
	    gameBoard = new JPanel();
	    gameBoard.setOpaque(true);
	    gameBoard.setBackground(Color.WHITE);
	    gameBoard.add(gameboardView.getLeftPanel());
	  
	   
	   c.fill = GridBagConstraints.BOTH;

	    c.gridx = 0;
	    c.gridy = 1;
	    c.gridwidth = 1;
	  
	    c.weightx = 1;
	  c.weighty = 4;
	    add(gameBoard,c);
	    
	 
	    centerPanel = new JPanel();
	    centerPanel.setLayout(new BorderLayout());
	    centerPanel.setOpaque(true);
	    centerPanel.add(playerView.getPanel(),BorderLayout.EAST);
	    centerPanel.add(propView.getPanel(),BorderLayout.WEST);
	    centerPanel.add(gameboardView.getPanel());
	   
	   
	   c.fill = GridBagConstraints.BOTH;
	 
	   c.gridwidth = 2;
	    c.gridx = 1;
	    c.gridy = 1;
	    c.weightx = 4;
	  c.weighty =4;
	   
	    add(centerPanel,c);
	    
	  
	   
	    gameBoard = new JPanel();
	    gameBoard.setOpaque(true);
	    gameBoard.setBackground(Color.WHITE);
	    gameBoard.add(gameboardView.getRightPanel());
	   
	  
	   c.fill = GridBagConstraints.BOTH;
	   c.gridwidth = 1;
	    c.gridx =4;
	    c.gridy = 1;
	    c.weightx = 1;
	  c.weighty = 4;
	   
	   
	    add(gameBoard,c);
	}
	

}
